#include "cgen_framework.h"

// --- SBO Vector Header Template ---
const char *SBOVEC_TEMPLATE_H = 
    "#pragma once\n"
    "#ifndef SBOVEC_{{00BU}}_H\n"
    "#define SBOVEC_{{00BU}}_H\n\n"
    "#include <stddef.h>\n"
    "#include <stdbool.h>\n\n"
    "/**\n"
    " * @brief A Small-Buffer Optimized (SBO) type-safe contiguous array container.\n"
    " * @details Can borrow local scratch memory before seamlessly graduating to heap allocations.\n"
    " */\n"
    "typedef struct {\n"
    "    {{00}} *data;    /**< Pointer to active element storage (stack array or heap block). */\n"
    "    size_t len;      /**< Current number of elements stored in the vector. */\n"
    "    size_t cap;      /**< Total active element capacity threshold. */\n"
    "    bool is_heap;    /**< Flag indicating if storage ownership requires heap deallocation. */\n"
    "} sbovec_{{00B}}_t;\n\n"
    "/**\n"
    " * @brief Initializes an empty SBO vector instance without an initial local buffer.\n"
    " * @param v Pointer to the target vector structure.\n"
    " */\n"
    "void sbovec_{{00B}}_init(sbovec_{{00B}}_t *v);\n\n"
    "/**\n"
    " * @brief Initializes an SBO vector tied to an externally managed memory buffer.\n"
    " * @note The container will use this buffer zero-allocation style until its capacity is exceeded.\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @param ext_buf Pointer to a local scratchpad or stack array to utilize as initial storage.\n"
    " * @param ext_cap The number of elements the provided external buffer can hold.\n"
    " */\n"
    "void sbovec_{{00B}}_init_with_buf(sbovec_{{00B}}_t *v, {{00}} *ext_buf, size_t ext_cap);\n\n"
    "/**\n"
    " * @brief Safely drops allocations. Only executes free() if storage escalated to the heap.\n"
    " * @param v Pointer to the target vector structure.\n"
    " */\n"
    "void sbovec_{{00B}}_free(sbovec_{{00B}}_t *v);\n\n"
    "/**\n"
    " * @brief Ensures space for at least the specified capacity. Triggers heap escalation if required.\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @param new_cap The minimum number of elements to reserve space for.\n"
    " */\n"
    "void sbovec_{{00B}}_reserve(sbovec_{{00B}}_t *v, size_t new_cap);\n\n"
    "/**\n"
    " * @brief Modifies the logical length boundary of the vector container.\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @param new_len The new element count boundary.\n"
    " */\n"
    "void sbovec_{{00B}}_resize(sbovec_{{00B}}_t *v, size_t new_len);\n\n"
    "/**\n"
    " * @brief Appends a new element onto the end of the vector container.\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @param val The element value to copy into the vector.\n"
    " */\n"
    "void sbovec_{{00B}}_append(sbovec_{{00B}}_t *v, {{00}} val);\n\n"
    "/**\n"
    " * @brief Appends a new element onto the end of the vector container (synonym for append).\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @param val The element value to copy into the vector.\n"
    " */\n"
    "void sbovec_{{00B}}_push(sbovec_{{00B}}_t *v, {{00}} val);\n\n"
    "/**\n"
    " * @brief Removes the final element from the vector container.\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @return true if an element was successfully popped, false if the vector was empty.\n"
    " */\n"
    "bool sbovec_{{00B}}_pop(sbovec_{{00B}}_t *v);\n\n"
    "/**\n"
    " * @brief Obtains a direct pointer to the final element in the vector container.\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @return Pointer to the last element, or NULL if the vector is empty.\n"
    " */\n"
    "{{00}} *sbovec_{{00B}}_back(sbovec_{{00B}}_t *v);\n\n"
    "/**\n"
    " * @brief Appends a contiguous block of multiple elements onto the end of the vector.\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @param items Pointer to the source continuous array of elements.\n"
    " * @param count The number of elements to copy from the source buffer.\n"
    " */\n"
    "void sbovec_{{00B}}_append_range(sbovec_{{00B}}_t *v, const {{00}} *items, size_t count);\n\n"
    "#endif\n";

// --- SBO Vector Implementation Template ---
const char *SBOVEC_TEMPLATE_C = 
    "#include \"sbovec_{{00B}}.h\"\n"
    "#include <stdlib.h>\n\n"
    "void sbovec_{{00B}}_init(sbovec_{{00B}}_t *v) {\n"
    "    v->data = NULL;\n"
    "    v->len = 0;\n"
    "    v->cap = 0;\n"
    "    v->is_heap = false;\n"
    "}\n\n"
    "void sbovec_{{00B}}_init_with_buf(sbovec_{{00B}}_t *v, {{00}} *ext_buf, size_t ext_cap) {\n"
    "    v->data = ext_buf;\n"
    "    v->len = 0;\n"
    "    v->cap = ext_cap;\n"
    "    v->is_heap = false;\n"
    "}\n\n"
    "void sbovec_{{00B}}_free(sbovec_{{00B}}_t *v) {\n"
    "    if (v->is_heap && v->data != NULL) {\n"
    "        free(v->data);\n"
    "    }\n"
    "    v->data = NULL;\n"
    "    v->len = 0;\n"
    "    v->cap = 0;\n"
    "    v->is_heap = false;\n"
    "}\n\n"
    "void sbovec_{{00B}}_reserve(sbovec_{{00B}}_t *v, size_t new_cap) {\n"
    "    if (new_cap <= v->cap) {\n"
    "        return;\n"
    "    }\n"
    "    {{00}} *new_data = ({{00}} *)malloc(new_cap * sizeof({{00}}));\n"
    "    if (new_data == NULL && new_cap > 0) {\n"
    "        abort();\n"
    "    }\n"
    "    if (v->len > 0 && v->data != NULL) {\n"
    "        for (size_t i = 0; i < v->len; i++) {\n"
    "            new_data[i] = v->data[i];\n"
    "        }\n"
    "    }\n"
    "    if (v->is_heap && v->data != NULL) {\n"
    "        free(v->data);\n"
    "    }\n"
    "    v->data = new_data;\n"
    "    v->cap = new_cap;\n"
    "    v->is_heap = true;\n"
    "}\n\n"
    "void sbovec_{{00B}}_resize(sbovec_{{00B}}_t *v, size_t new_len) {\n"
    "    if (new_len > v->cap) {\n"
    "        sbovec_{{00B}}_reserve(v, new_len);\n"
    "    }\n"
    "    v->len = new_len;\n"
    "}\n\n"
    "void sbovec_{{00B}}_append(sbovec_{{00B}}_t *v, {{00}} val) {\n"
    "    if (v->len >= v->cap) {\n"
    "        size_t new_cap = v->cap == 0 ? 4 : v->cap * 2;\n"
    "        sbovec_{{00}}_reserve(v, new_cap);\n"
    "    }\n"
    "    v->data[v->len] = val;\n"
    "    v->len++;\n"
    "}\n\n"
    "void sbovec_{{00B}}_push(sbovec_{{00B}}_t *v, {{00}} val) {\n"
    "    sbovec_{{00}}_append(v, val);\n"
    "}\n\n"
    "bool sbovec_{{00B}}_pop(sbovec_{{00B}}_t *v) {\n"
    "    if (v->len == 0) {\n"
    "        return false;\n"
    "    }\n"
    "    v->len--;\n"
    "    return true;\n"
    "}\n\n"
    "{{00}} *sbovec_{{00B}}_back(sbovec_{{00B}}_t *v) {\n"
    "    if (v->len == 0) {\n"
    "        return NULL;\n"
    "    }\n"
    "    return &v->data[v->len - 1];\n"
    "}\n\n"
    "void sbovec_{{00B}}_append_range(sbovec_{{00B}}_t *v, const {{00}} *items, size_t count) {\n"
    "    if (count == 0 || items == NULL) return;\n"
    "    if (v->len + count > v->cap) {\n"
    "        sbovec_{{00B}}_reserve(v, v->len + count);\n"
    "    }\n"
    "    for (size_t i = 0; i < count; i++) {\n"
    "        v->data[v->len + i] = items[i];\n"
    "    }\n"
    "    v->len += count;\n"
    "}\n";

int main(int argc, char **argv) {
    cgen_app_def_t app = {
        .subcommand_name = "sbovec",
        .opt_spec        = "=ttypename",
        .template_h      = SBOVEC_TEMPLATE_H,
        .template_c      = SBOVEC_TEMPLATE_C
    };

    return cgen_app_run(&app, argc - 1, argv + 1);
}
