#include <string.h>
#include "cgen_framework.h"

// ============================================================================
// 1. HEADER ASSET TEMPLATE (WITH FULL DOXYGEN DOCUMENTATION)
// ============================================================================
const char *PQUEUE_TEMPLATE_H =
    "#pragma once\n"
    "#ifndef PQUEUE_{{00BU}}_H\n"
    "#define PQUEUE_{{00BU}}_H\n\n"
    "#include <stddef.h>\n"
    "#include <stdbool.h>\n\n"
    "/**\n"
    " * @brief Function pointer signature for evaluating element priority.\n"
    " *\n"
    " * The user-defined comparison function dictates the structural heap policy (Max-Heap vs Min-Heap).\n"
    " *\n"
    " * @param a Pointer to the first element to evaluate.\n"
    " * @param b Pointer to the second element to evaluate.\n"
    " * @return A positive integer if 'a' has higher priority than 'b',\n"
    " * a negative integer if 'b' has higher priority, or 0 if equal.\n"
    " */\n"
    "typedef int (*pqueue_{{00B}}_cmp_fn)(const {{00}} *a, const {{00}} *b);\n\n"
    "/**\n"
    " * @brief A dynamic, array-backed binary heap priority queue.\n"
    " */\n"
    "typedef struct {\n"
    "    {{00}} *data;                  /**< Contiguous internal storage array. */\n"
    "    size_t len;                   /**< Current number of elements in the heap. */\n"
    "    size_t cap;                   /**< Total allocated capacity footprint. */\n"
    "    pqueue_{{00B}}_cmp_fn cmp;     /**< Cached comparison policy routing. */\n"
    "} pqueue_{{00B}}_t;\n\n"
    
    "/**\n"
    " * @brief Initializes a priority queue instance with a custom evaluation policy.\n"
    " *\n"
    " * Sets up the container in a clean zero-state. Memory allocation is deferred\n"
    " * until the first push operation is executed to minimize startup overhead.\n"
    " *\n"
    " * @param pq Pointer to the priority queue instance to initialize.\n"
    " * @param cmp The comparison function pointer defining the priority policy.\n"
    " */\n"
    "void pqueue_{{00B}}_init(pqueue_{{00B}}_t *pq, pqueue_{{00B}}_cmp_fn cmp);\n\n"
    
    "/**\n"
    " * @brief Deep cleans the internal buffer and zeroes out tracking states.\n"
    " *\n"
    " * Frees the dynamically allocated array and returns the structure to a zero-state\n"
    " * to safeguard against dangling pointers.\n"
    " *\n"
    " * @param pq Pointer to the active priority queue instance to clean up.\n"
    " */\n"
    "void pqueue_{{00B}}_free(pqueue_{{00B}}_t *pq);\n\n"
    
    "/**\n"
    " * @brief Inserts an item into the queue, dynamically maintaining heap ordering.\n"
    " *\n"
    " * Appends the item to the end of the internal array and triggers a geometric growth\n"
    " * resize if capacity limits are breached. The element is then sifted upward\n"
    " * to preserve the structural heap invariant.\n"
    " *\n"
    " * @param pq Pointer to the active priority queue instance.\n"
    " * @param item The element payload to push into the queue.\n"
    " * @return true if the insertion and potential allocation succeeded; false if a realloc fails.\n"
    " */\n"
    "bool pqueue_{{00B}}_push(pqueue_{{00B}}_t *pq, {{00}} item);\n\n"
    
    "/**\n"
    " * @brief Extracts the absolute highest priority item from the root of the heap.\n"
    " *\n"
    " * Grabs the element at index 0, shifts the last element of the array to the root,\n"
    " * and sifts it downward to rebalance the binary tree layout.\n"
    " *\n"
    " * @param pq Pointer to the active priority queue instance.\n"
    " * @param out_item Pointer to a storage destination where the popped value will be written.\n"
    " * Can be safely set to NULL if you merely wish to discard the root item.\n"
    " * @return true if an item was successfully extracted; false if the queue is completely empty.\n"
    " */\n"
    "bool pqueue_{{00B}}_pop(pqueue_{{00B}}_t *pq, {{00}} *out_item);\n\n"
    "#endif\n";

// ============================================================================
// 2. SOURCE ASSET TEMPLATE
// ============================================================================
const char *PQUEUE_TEMPLATE_C =
    "#include <stdlib.h>\n"
    "#include \"pqueue_{{00B}}.h\"\n\n"
    
    "void pqueue_{{00B}}_init(pqueue_{{00B}}_t *pq, pqueue_{{00B}}_cmp_fn cmp) {\n"
    "    if (pq == NULL) return;\n"
    "    pq->data = NULL;\n"
    "    pq->len = 0;\n"
    "    pq->cap = 0;\n"
    "    pq->cmp = cmp;\n"
    "}\n\n"
    
    "void pqueue_{{00B}}_free(pqueue_{{00B}}_t *pq) {\n"
    "    if (pq == NULL) return;\n"
    "    if (pq->data != NULL) {\n"
    "        free(pq->data);\n"
    "        pq->data = NULL;\n"
    "    }\n"
    "    pq->len = 0;\n"
    "    pq->cap = 0;\n"
    "    pq->cmp = NULL;\n"
    "}\n\n"
    
    "static void sift_up(pqueue_{{00B}}_t *pq, size_t idx) {\n"
    "    while (idx > 0) {\n"
    "        size_t parent = (idx - 1) / 2;\n"
    "        // If parent priority is greater than or equal to current, heap is stable\n"
    "        if (pq->cmp(&pq->data[parent], &pq->data[idx]) >= 0) {\n"
    "            break;\n"
    "        }\n"
    "        // Otherwise, swap and climb\n"
    "        {{00}} tmp = pq->data[parent];\n"
    "        pq->data[parent] = pq->data[idx];\n"
    "        pq->data[idx] = tmp;\n"
    "        idx = parent;\n"
    "    }\n"
    "}\n\n"
    
    "static void sift_down(pqueue_{{00B}}_t *pq, size_t idx) {\n"
    "    size_t half = pq->len / 2;\n"
    "    while (idx < half) {\n"
    "        size_t left = 2 * idx + 1;\n"
    "        size_t right = left + 1;\n"
    "        size_t highest = left;\n"
    "        \n"
    "        // Determine which of the two children has higher priority\n"
    "        if (right < pq->len && pq->cmp(&pq->data[right], &pq->data[left]) > 0) {\n"
    "            highest = right;\n"
    "        }\n"
    "        // If parent is higher priority than the largest child, we are done\n"
    "        if (pq->cmp(&pq->data[idx], &pq->data[highest]) >= 0) {\n"
    "            break;\n"
    "        }\n"
    "        // Swap parent down and dive\n"
    "        {{00}} tmp = pq->data[idx];\n"
    "        pq->data[idx] = pq->data[highest];\n"
    "        pq->data[highest] = tmp;\n"
    "        idx = highest;\n"
    "    }\n"
    "}\n\n"
    
    "bool pqueue_{{00B}}_push(pqueue_{{00B}}_t *pq, {{00}} item) {\n"
    "    if (pq == NULL || pq->cmp == NULL) return false;\n"
    "    \n"
    "    // Handle dynamic geometric growth envelope\n"
    "    if (pq->len == pq->cap) {\n"
    "        size_t new_cap = pq->cap == 0 ? 4 : pq->cap * 2;\n"
    "        {{00}} *new_data = realloc(pq->data, sizeof({{00}}) * new_cap);\n"
    "        if (new_data == NULL) return false;\n"
    "        pq->data = new_data;\n"
    "        pq->cap = new_cap;\n"
    "    }\n"
    "    \n"
    "    pq->data[pq->len] = item;\n"
    "    sift_up(pq, pq->len);\n"
    "    pq->len++;\n"
    "    return true;\n"
    "}\n\n"
    
    "bool pqueue_{{00B}}_pop(pqueue_{{00B}}_t *pq, {{00}} *out_item) {\n"
    "    if (pq == NULL || pq->data == NULL || pq->len == 0) return false;\n"
    "    \n"
    "    if (out_item != NULL) {\n"
    "        *out_item = pq->data[0]; // Highest priority item is always at root\n"
    "    }\n"
    "    \n"
    "    pq->len--;\n"
    "    if (pq->len > 0) {\n"
    "        pq->data[0] = pq->data[pq->len]; // Move last element to root\n"
    "        sift_down(pq, 0);               // Rebalance the heap tree\n"
    "    }\n"
    "    return true;\n"
    "}\n";

// ============================================================================
// 3. APPLICATION ENTRYPOINT
// ============================================================================
int main(int argc, char **argv) {
    cgen_app_def_t app = {
        .subcommand_name = "pqueue",
        .opt_spec        = "=ttypename",
        .template_h      = PQUEUE_TEMPLATE_H,
        .template_c      = PQUEUE_TEMPLATE_C
    };
    return cgen_app_run(&app, argc - 1, argv + 1);
}
