#include "cgen_framework.h"

// ============================================================================
// 1. B-TREE MAP HEADER ASSET TEMPLATE
// ============================================================================
const char *BTREE_TEMPLATE_H =
    "#pragma once\n"
    "#ifndef BTREE_{{KEY_BU}}_{{VAL_BU}}_H\n"
    "#define BTREE_{{KEY_BU}}_{{VAL_BU}}_H\n\n"
    "#include <stddef.h>\n"
    "#include <stdbool.h>\n\n"
    "/**\n"
    " * @brief Function pointer signature for evaluating key ordering.\n"
    " * @return Positive if a > b, negative if a < b, 0 if equal.\n"
    " */\n"
    "typedef int (*btree_{{KEY_B}}_{{VAL_B}}_cmp_fn)(const {{KEY}} *a, const {{KEY}} *b);\n\n"
    "/**\n"
    " * @brief An internal multi-way search tree node for the Order 4 B-Tree.\n"
    " */\n"
    "typedef struct btree_{{KEY_B}}_{{VAL_B}}_node_s {\n"
    "    bool is_leaf;\n"
    "    size_t num_keys;\n"
    "    {{KEY}} keys[3];\n"
    "    {{VAL}} vals[3];\n"
    "    struct btree_{{KEY_B}}_{{VAL_B}}_node_s *children[4];\n"
    "} btree_{{KEY_B}}_{{VAL_B}}_node_t;\n\n"
    "/**\n"
    " * @brief A cache-dense, strictly ordered B-Tree map container.\n"
    " */\n"
    "typedef struct {\n"
    "    btree_{{KEY_B}}_{{VAL_B}}_node_t *root;\n"
    "    size_t count;\n"
    "    btree_{{KEY_B}}_{{VAL_B}}_cmp_fn cmp;\n"
    "} btree_{{KEY_B}}_{{VAL_B}}_t;\n\n"
    
    "void btree_{{KEY_B}}_{{VAL_B}}_init(btree_{{KEY_B}}_{{VAL_B}}_t *map, btree_{{KEY_B}}_{{VAL_B}}_cmp_fn cmp);\n"
    "void btree_{{KEY_B}}_{{VAL_B}}_free(btree_{{KEY_B}}_{{VAL_B}}_t *map);\n"
    "bool btree_{{KEY_B}}_{{VAL_B}}_insert(btree_{{KEY_B}}_{{VAL_B}}_t *map, {{KEY}} key, {{VAL}} val);\n"
    "bool btree_{{KEY_B}}_{{VAL_B}}_get(const btree_{{KEY_B}}_{{VAL_B}}_t *map, {{KEY}} key, {{VAL}} *out_val);\n"
    "bool btree_{{KEY_B}}_{{VAL_B}}_contains(const btree_{{KEY_B}}_{{VAL_B}}_t *map, {{KEY}} key);\n\n"
    "#endif\n";

// ============================================================================
// 2. B-TREE MAP SOURCE IMPLEMENTATION TEMPLATE
// ============================================================================
const char *BTREE_TEMPLATE_C =
    "#include <stdio.h>\n"
    "#include <stdlib.h>\n"
    "#include <string.h>\n"
    "#include \"btree_{{KEY_B}}_{{VAL_B}}.h\"\n\n"
    
    "static btree_{{KEY_B}}_{{VAL_B}}_node_t *node_create(bool is_leaf) {\n"
    "    btree_{{KEY_B}}_{{VAL_B}}_node_t *node = (btree_{{KEY_B}}_{{VAL_B}}_node_t *)malloc(sizeof(btree_{{KEY_B}}_{{VAL_B}}_node_t));\n"
    "    if (node == NULL) return NULL;\n"
    "    node->is_leaf = is_leaf;\n"
    "    node->num_keys = 0;\n"
    "    for (int i = 0; i < 4; i++) node->children[i] = NULL;\n"
    "    return node;\n"
    "}\n\n"
    
    "static void node_free_recursive(btree_{{KEY_B}}_{{VAL_B}}_node_t *node) {\n"
    "    if (node == NULL) return;\n"
    "    if (node->is_leaf == false) {\n"
    "        for (size_t i = 0; i <= node->num_keys; i++) {\n"
    "            if (node->children[i] != NULL) {\n"
    "                node_free_recursive(node->children[i]);\n"
    "                node->children[i] = NULL;\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    free(node);\n"
    "}\n\n"
    
    "static void split_child(btree_{{KEY_B}}_{{VAL_B}}_node_t *parent, size_t child_idx) {\n"
    "    btree_{{KEY_B}}_{{VAL_B}}_node_t *full_child = parent->children[child_idx];\n"
    "    btree_{{KEY_B}}_{{VAL_B}}_node_t *right_sibling = node_create(full_child->is_leaf);\n"
    "    if (right_sibling == NULL) return;\n\n"
    "    right_sibling->num_keys = 1;\n"
    "    right_sibling->keys[0] = full_child->keys[2];\n"
    "    right_sibling->vals[0] = full_child->vals[2];\n\n"
    "    if (full_child->is_leaf == false) {\n"
    "        right_sibling->children[0] = full_child->children[2];\n"
    "        right_sibling->children[1] = full_child->children[3];\n"
    "        full_child->children[2] = NULL;\n"
    "        full_child->children[3] = NULL;\n"
    "    }\n\n"
    "    full_child->num_keys = 1;\n\n"
    "    for (size_t i = parent->num_keys + 1; i > child_idx + 1; i--) {\n"
    "        parent->children[i] = parent->children[i - 1];\n"
    "    }\n"
    "    parent->children[child_idx + 1] = right_sibling;\n\n"
    "    for (size_t i = parent->num_keys; i > child_idx; i--) {\n"
    "        parent->keys[i] = parent->keys[i - 1];\n"
    "        parent->vals[i] = parent->vals[i - 1];\n"
    "    }\n\n"
    "    parent->keys[child_idx] = full_child->keys[1];\n"
    "    parent->vals[child_idx] = full_child->vals[1];\n"
    "    parent->num_keys++;\n"
    "}\n\n"
    
    "static bool insert_non_full(btree_{{KEY_B}}_{{VAL_B}}_node_t *node, {{KEY}} key, {{VAL}} val, btree_{{KEY_B}}_{{VAL_B}}_cmp_fn cmp) {\n"
    "    size_t i = node->num_keys;\n"
    "    if (node->is_leaf == true) {\n"
    "        while (i > 0 && cmp(&key, &node->keys[i - 1]) <= 0) {\n"
    "            if (cmp(&node->keys[i - 1], &key) == 0) {\n"
    "                node->vals[i - 1] = val;\n"
    "                return false;\n"
    "            }\n"
    "            i--;\n"
    "        }\n"
    "        for (size_t j = node->num_keys; j > i; j--) {\n"
    "            node->keys[j] = node->keys[j - 1];\n"
    "            node->vals[j] = node->vals[j - 1];\n"
    "        }\n"
    "        node->keys[i] = key;\n"
    "        node->vals[i] = val;\n"
    "        node->num_keys++;\n"
    "        return true;\n"
    "    } else {\n"
    "        while (i > 0 && cmp(&key, &node->keys[i - 1]) < 0) {\n"
    "            i--;\n"
    "        }\n"
    "        if (i > 0 && cmp(&node->keys[i - 1], &key) == 0) {\n"
    "            node->vals[i - 1] = val;\n"
    "            return false;\n"
    "        }\n"
    "        if (node->children[i]->num_keys == 3) {\n"
    "            split_child(node, i);\n"
    "            if (cmp(&key, &node->keys[i]) > 0) {\n"
    "                i++;\n"
    "            } else if (cmp(&key, &node->keys[i]) == 0) {\n"
    "                node->vals[i] = val;\n"
    "                return false;\n"
    "            }\n"
    "        }\n"
    "        return insert_non_full(node->children[i], key, val, cmp);\n"
    "    }\n"
    "}\n\n"
    
    "void btree_{{KEY_B}}_{{VAL_B}}_init(btree_{{KEY_B}}_{{VAL_B}}_t *map, btree_{{KEY_B}}_{{VAL_B}}_cmp_fn cmp) {\n"
    "    if (map == NULL) return;\n"
    "    map->root = NULL;\n"
    "    map->count = 0;\n"
    "    map->cmp = cmp;\n"
    "}\n\n"
    
    "void btree_{{KEY_B}}_{{VAL_B}}_free(btree_{{KEY_B}}_{{VAL_B}}_t *map) {\n"
    "    if (map == NULL) return;\n"
    "    if (map->root != NULL) {\n"
    "        node_free_recursive(map->root);\n"
    "        map->root = NULL;\n"
    "    }\n"
    "    map->count = 0;\n"
    "}\n\n"
    
    "bool btree_{{KEY_B}}_{{VAL_B}}_insert(btree_{{KEY_B}}_{{VAL_B}}_t *map, {{KEY}} key, {{VAL}} val) {\n"
    "    if (map == NULL || map->cmp == NULL) return false;\n"
    "    if (map->root == NULL) {\n"
    "        map->root = node_create(true);\n"
    "        if (map->root == NULL) return false;\n"
    "        map->root->keys[0] = key;\n"
    "        map->root->vals[0] = val;\n"
    "        map->root->num_keys = 1;\n"
    "        map->count = 1;\n"
    "        return true;\n"
    "    }\n"
    "    if (map->root->num_keys == 3) {\n"
    "        btree_{{KEY_B}}_{{VAL_B}}_node_t *new_root = node_create(false);\n"
    "        if (new_root == NULL) return false;\n"
    "        new_root->children[0] = map->root;\n"
    "        map->root = new_root;\n"
    "        split_child(new_root, 0);\n"
    "    }\n"
    "    bool is_new = insert_non_full(map->root, key, val, map->cmp);\n"
    "    if (is_new) map->count++;\n"
    "    return true;\n"
    "}\n\n"
    
    "bool btree_{{KEY_B}}_{{VAL_B}}_get(const btree_{{KEY_B}}_{{VAL_B}}_t *map, {{KEY}} key, {{VAL}} *out_val) {\n"
    "    if (map == NULL || map->root == NULL || map->cmp == NULL) return false;\n"
    "    btree_{{KEY_B}}_{{VAL_B}}_node_t *curr = map->root;\n"
    "    while (curr != NULL) {\n"
    "        size_t i = 0;\n"
    "        while (i < curr->num_keys && map->cmp(&key, &curr->keys[i]) > 0) i++;\n"
    "        if (i < curr->num_keys && map->cmp(&curr->keys[i], &key) == 0) {\n"
    "            if (out_val != NULL) *out_val = curr->vals[i];\n"
    "            return true;\n"
    "        }\n"
    "        if (curr->is_leaf) break;\n"
    "        curr = curr->children[i];\n"
    "    }\n"
    "    return false;\n"
    "}\n\n"
    
    "bool btree_{{KEY_B}}_{{VAL_B}}_contains(const btree_{{KEY_B}}_{{VAL_B}}_t *map, {{KEY}} key) {\n"
    "    return btree_{{KEY_B}}_{{VAL_B}}_get(map, key, NULL);\n"
    "}\n";

// ============================================================================
// 3. APPLICATION ENTRYPOINT
// ============================================================================
int main(int argc, char **argv) {
    cgen_app_dual_def_t app = {
        .subcommand_name = "btree",
        .template_h      = BTREE_TEMPLATE_H,
        .template_c      = BTREE_TEMPLATE_C
    };
    return cgen_app_run_dual(&app, argc, argv);
}
