#include "cgen_framework.h"

// --- Header Template Matching pstr_vec_t Naming ---
const char *VEC_TEMPLATE_H = 
    "#pragma once\n"
    "#ifndef VEC_{{00BU}}_H\n"
    "#define VEC_{{00BU}}_H\n\n"
    "#include <stddef.h>\n"
    "#include <stdbool.h>\n\n"
    "/**\n"
    " * @brief A type-safe, dynamically resizing contiguous array container.\n"
    " */\n"
    "typedef struct {\n"
    "    {{00}} *data; /**< Pointer to the underlying element array. */\n"
    "    size_t len;   /**< Current number of elements stored in the vector. */\n"
    "    size_t cap;   /**< Total allocated element capacity of the vector. */\n"
    "} vec_{{00B}}_t;\n\n"
    "/**\n"
    " * @brief Initializes an empty vector instance.\n"
    " * @param v Pointer to the target vector structure.\n"
    " */\n"
    "void vec_{{00B}}_init(vec_{{00B}}_t *v);\n\n"
    "/**\n"
    " * @brief Frees all dynamically allocated memory held by the vector.\n"
    " * @param v Pointer to the target vector structure.\n"
    " */\n"
    "void vec_{{00B}}_free(vec_{{00B}}_t *v);\n\n"
    "/**\n"
    " * @brief Ensures the vector has allocated space for at least the specified capacity.\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @param new_cap The minimum number of elements to reserve space for.\n"
    " */\n"
    "void vec_{{00B}}_reserve(vec_{{00B}}_t *v, size_t new_cap);\n\n"
    "/**\n"
    " * @brief Modifies the logical length of the vector, growing capacity if necessary.\n"
    " * @note Newly provisioned slots remain uninitialized.\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @param new_len The new element count boundary.\n"
    " */\n"
    "void vec_{{00B}}_resize(vec_{{00B}}_t *v, size_t new_len);\n\n"
    "/**\n"
    " * @brief Appends a new element onto the end of the vector.\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @param val The element value to copy into the vector.\n"
    " */\n"
    "void vec_{{00B}}_append(vec_{{00B}}_t *v, {{00}} val);\n\n"
    "/**\n"
    " * @brief Appends a new element onto the end of the vector (synonym for append).\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @param val The element value to copy into the vector.\n"
    " */\n"
    "void vec_{{00B}}_push(vec_{{00B}}_t *v, {{00}} val);\n\n"
    "/**\n"
    " * @brief Removes the final element from the vector.\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @return true if an element was successfully popped, false if the vector was empty.\n"
    " */\n"
    "bool vec_{{00B}}_pop(vec_{{00B}}_t *v);\n\n"
    "/**\n"
    " * @brief Obtains a direct pointer to the final element in the vector.\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @return Pointer to the last element, or NULL if the vector is empty.\n"
    " */\n"
    "{{00}} *vec_{{00B}}_back(vec_{{00B}}_t *v);\n\n"
    "/**\n"
    " * @brief Appends a contiguous block of multiple elements onto the end of the vector.\n"
    " * @param v Pointer to the target vector structure.\n"
    " * @param items Pointer to the source continuous array of elements.\n"
    " * @param count The number of elements to copy from the source buffer.\n"
    " */\n"
    "void vec_{{00B}}_append_range(vec_{{00B}}_t *v, const {{00}} *items, size_t count);\n\n"
    "/**\n"
    "  * @brief Function pointer signature for freeing internal element resources.\n"
    "  * @param item Direct pointer to the element container within the array.\n"
    "  */\n"
    " typedef void (*vec_{{00B}}_free_fn)({{00}} *item);\n"
    "/**\n"
    "  * @brief Iterates through the vector, applying a custom cleanup function to each\n"
    "  * element before freeing the underlying vector array itself.\n"
    "  * @param v Pointer to the target vector structure.\n"
    "  * @param f Function pointer to the element destructor (can be NULL for shallow free).\n"
    "  */\n"
    " void vec_{{00B}}_deep_free(vec_{{00B}}_t *v, vec_{{00B}}_free_fn f);\n"
    "#endif\n";

// --- Upgraded Implementation Template ---
const char *VEC_TEMPLATE_C = 
    "#include \"vec_{{00B}}.h\"\n"
    "#include <stdlib.h>\n\n"
    "void vec_{{00B}}_init(vec_{{00B}}_t *v) {\n"
    "    v->data = NULL;\n"
    "    v->len = 0;\n"
    "    v->cap = 0;\n"
    "}\n\n"
    "void vec_{{00B}}_free(vec_{{00B}}_t *v) {\n"
    "    if (v->data != NULL) {\n"
    "        free(v->data);\n"
    "        v->data = NULL;\n"
    "    }\n"
    "    v->len = 0;\n"
    "    v->cap = 0;\n"
    "}\n\n"
    "void vec_{{00B}}_reserve(vec_{{00B}}_t *v, size_t new_cap) {\n"
    "    if (new_cap <= v->cap) {\n"
    "        return;\n"
    "    }\n"
    "    {{00}} *new_data = ({{00}} *)realloc(v->data, new_cap * sizeof({{00}}));\n"
    "    if (new_data == NULL && new_cap > 0) {\n"
    "        abort();\n"
    "    }\n"
    "    v->data = new_data;\n"
    "    v->cap = new_cap;\n"
    "}\n\n"
    "void vec_{{00B}}_resize(vec_{{00B}}_t *v, size_t new_len) {\n"
    "    if (new_len > v->cap) {\n"
    "        vec_{{00B}}_reserve(v, new_len);\n"
    "    }\n"
    "    v->len = new_len;\n"
    "}\n\n"
    "void vec_{{00B}}_append(vec_{{00B}}_t *v, {{00}} val) {\n"
    "    if (v->len >= v->cap) {\n"
    "        size_t new_cap = v->cap == 0 ? 4 : v->cap * 2;\n"
    "        vec_{{00B}}_reserve(v, new_cap);\n"
    "    }\n"
    "    v->data[v->len] = val;\n"
    "    v->len++;\n"
    "}\n\n"
    "void vec_{{00B}}_push(vec_{{00B}}_t *v, {{00}} val) {\n"
    "    vec_{{00B}}_append(v, val);\n"
    "}\n\n"
    "bool vec_{{00B}}_pop(vec_{{00B}}_t *v) {\n"
    "    if (v->len == 0) {\n"
    "        return false;\n"
    "    }\n"
    "    v->len--;\n"
    "    return true;\n"
    "}\n\n"
    "{{00}} *vec_{{00B}}_back(vec_{{00B}}_t *v) {\n"
    "    if (v->len == 0) {\n"
    "        return NULL;\n"
    "    }\n"
    "    return &v->data[v->len - 1];\n"
    "}\n\n"
    "void vec_{{00B}}_append_range(vec_{{00B}}_t *v, const {{00}} *items, size_t count) {\n"
    "    if (count == 0 || items == NULL) return;\n"
    "    if (v->len + count > v->cap) {\n"
    "        vec_{{00B}}_reserve(v, v->len + count);\n"
    "    }\n"
    "    for (size_t i = 0; i < count; i++) {\n"
    "        v->data[v->len + i] = items[i];\n"
    "    }\n"
    "    v->len += count;\n"
    "}\n"
    "void vec_{{00B}}_deep_free(vec_{{00B}}_t *v, vec_{{00B}}_free_fn f) {\n"
    "    if (v == NULL) {\n"
    "        return;\n"
    "    }\n"
    "    if (f != NULL) {\n"
    "        for (size_t i = 0; i < v->len; i++) {\n"
    "            f(&v->data[i]);\n"
    "        }\n"
    "    }\n"
    "    vec_{{00B}}_free(v);\n"
    "}\n";

int main(int argc, char **argv) {
    cgen_app_def_t app = {
        .subcommand_name = "vec",
        .opt_spec        = "=ttypename", //
        .template_h      = VEC_TEMPLATE_H,
        .template_c      = VEC_TEMPLATE_C
    };

    // Forward arguments safely, skipping argv[0] to protect alignment bounds
    return cgen_app_run(&app, argc - 1, argv + 1);
}
